name: Release Redis Storage
 
on:
  push:
    tags:
      - "redis*"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/redis

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-nest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - name: Run tests
        run: deno test packages/redis/__tests__/deno.ts --allow-write --no-check --allow-read --unstable
      - name: Publish
        run: deno run --allow-read --allow-env --unstable eggs.ts redis