name: Release PSQL Storage
 
on:
  push:
    tags:
      - "psql*"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/psql

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}