name: Tests Redis Storage

on:
  push:
    paths:
      - packages/redis/**
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/redis

jobs:
  node-tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - name: install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: build
        run: pnpm run build
      - name: tests
        run: pnpm test
  deno-tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - name: Run tests
        run: deno test __tests__/deno.ts --allow-write --no-check --allow-read --unstable